[project]
name = "meli-challenge"
version = "0.1.0"
description = "Challenge - Scalable Scraping with GenAI Validation"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "scrapy>=2.13.3",
]

[dependency-groups]
dev = [
    "pytest>=8.4.1",
]
