service: meli-challenge
frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.11
  region: ${env:AWS_DEFAULT_REGION, 'us-east-1'}
  stage: ${env:STAGE, 'dev'}
  memorySize: 1024
  timeout: 300
  environment:
    DYNAMODB_TABLE_NAME: ${self:service}-${self:provider.stage}-products
    SQS_QUEUE_URL: !Ref ProductQueue
    ZYTE_API_KEY: ${env:ZYTE_API_KEY}
    SCRAPY_LOG_LEVEL: ${env:SCRAPY_LOG_LEVEL, 'INFO'}
    MAX_PAGES: ${env:MAX_PAGES, '20'}
    MAX_ITEMS: ${env:MAX_ITEMS, '2000'}
    MAX_BATCHES: ${env:MAX_BATCHES, '50'}
    MAX_MESSAGES_PER_BATCH: ${env:MAX_MESSAGES_PER_BATCH, '10'}
    MAX_RETRIES: ${env:MAX_RETRIES, '3'}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
            - dynamodb:Query
            - dynamodb:Scan
          Resource: 
            - !GetAtt ProductsTable.Arn
            - !Sub "${ProductsTable.Arn}/index/*"
        - Effect: Allow
          Action:
            - sqs:SendMessage
            - sqs:ReceiveMessage
            - sqs:DeleteMessage
            - sqs:GetQueueAttributes
          Resource: !GetAtt ProductQueue.Arn
        - Effect: Allow
          Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
          Resource: "*"
        - Effect: Allow
          Action:
            - secretsmanager:GetSecretValue
          Resource: !Sub "arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:${self:service}-${self:provider.stage}-*"

# functions:
#   # Lambda function for identification spider
#   identification-spider:
#     handler: handlers/identification.handler
#     events:
#       - schedule:
#           rate: cron(0 */6 * * ? *)  # Every 6 hours
#           enabled: ${env:ENABLE_SCHEDULED_SCRAPING, 'false'}
#       - http:
#           path: /scrape/identify
#           method: post
#           cors: true
#     environment:
#       SPIDER_TYPE: identify
#       MAX_PAGES: ${env:MAX_PAGES, '20'}
#       MAX_ITEMS: ${env:MAX_ITEMS, '2000'}

#   # Lambda function for collection spider
#   collection-spider:
#     handler: handlers/collection.handler
#     events:
#       - sqs:
#           arn: !GetAtt ProductQueue.Arn
#           batchSize: 1
#           maximumBatchingWindow: 30
#     environment:
#       SPIDER_TYPE: collect
#       MAX_BATCHES: ${env:MAX_BATCHES, '50'}
#       MAX_MESSAGES_PER_BATCH: ${env:MAX_MESSAGES_PER_BATCH, '10'}
#       MAX_RETRIES: ${env:MAX_RETRIES, '3'}

#   # Lambda function for data validation
#   data-validator:
#     handler: handlers/validation.handler
#     events:
#       - sqs:
#           path: /scrape/identify
#           method: post
#           cors: true
#     environment:
#       VALIDATION_ENABLE_AI: ${env:VALIDATION_AI_PROVIDER, 'openai'}

#   # Lambda function for monitoring and alerts
#   monitoring:
#     handler: handlers/monitoring.handler
#     events:
#       - schedule:
#           rate: rate(5 minutes)
#           enabled: ${env:ENABLE_MONITORING, 'true'}
#     environment:
#       ALERT_WEBHOOK_URL: ${env:ALERT_WEBHOOK_URL, 'not_configured'}

resources:
  Resources:
    # DynamoDB Table for products
    ProductsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.DYNAMODB_TABLE_NAME}
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: seller_id
            AttributeType: S
          - AttributeName: url_id
            AttributeType: S
          - AttributeName: inserted_at
            AttributeType: S
        KeySchema:
          - AttributeName: seller_id
            KeyType: HASH
          - AttributeName: url_id
            KeyType: RANGE
        GlobalSecondaryIndexes:
          - IndexName: InsertedAtIndex
            KeySchema:
              - AttributeName: inserted_at
                KeyType: HASH
            Projection:
              ProjectionType: ALL
        TimeToLiveSpecification:
          AttributeName: ttl
          Enabled: true
        Tags:
          - Key: Environment
            Value: ${self:provider.stage}
          - Key: Service
            Value: ${self:service}

    # SQS Queue for product processing
    ProductQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ${self:service}-${self:provider.stage}-products
        VisibilityTimeout: 300
        MessageRetentionPeriod: 1209600  # 14 days
        RedrivePolicy:
          deadLetterTargetArn: !GetAtt ProductDeadLetterQueue.Arn
          maxReceiveCount: 3
        Tags:
          - Key: Environment
            Value: ${self:provider.stage}
          - Key: Service
            Value: ${self:service}

    # SQS Dead Letter Queue
    ProductDeadLetterQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ${self:service}-${self:provider.stage}-products-dlq
        MessageRetentionPeriod: 1209600  # 14 days
        Tags:
          - Key: Environment
            Value: ${self:provider.stage}
          - Key: Service
            Value: ${self:service}

    # SQS Queue for validation
    ValidationQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ${self:service}-${self:provider.stage}-validation
        VisibilityTimeout: 300
        MessageRetentionPeriod: 1209600  # 14 days
        Tags:
          - Key: Environment
            Value: ${self:provider.stage}
          - Key: Service
            Value: ${self:service}

    # CloudWatch Log Group
    LogGroup:
      Type: AWS::Logs::LogGroup
      Properties:
        LogGroupName: /aws/lambda/${self:service}-${self:provider.stage}
        RetentionInDays: 30

    # Secrets Manager for API keys
    ApiSecrets:
      Type: AWS::SecretsManager::Secret
      Properties:
        Name: ${self:service}-${self:provider.stage}-api-keys
        Description: API keys for Meli Challenge
        SecretString: !Sub |
          {
            "zyte_api_key": "${env:ZYTE_API_KEY}",
            "openai_api_key": "${env:OPENAI_API_KEY}"
          }

  Outputs:
    ProductsTableName:
      Description: DynamoDB table name
      Value: !Ref ProductsTable
      Export:
        Name: ${self:service}-${self:provider.stage}-table-name

    ProductQueueUrl:
      Description: SQS queue URL
      Value: !Ref ProductQueue
      Export:
        Name: ${self:service}-${self:provider.stage}-queue-url

    ValidationQueueUrl:
      Description: Validation queue URL
      Value: !Ref ValidationQueue
      Export:
        Name: ${self:service}-${self:provider.stage}-validation-queue-url

plugins:
  - serverless-dotenv-plugin

custom:
  # Python environment configuration
  pythonBin: .venv/bin/python
  requirementsFile: requirements.txt
  # Package optimization - only include essential files
  package:
    patterns:
      - "!**"
      - "handlers/**"
      - "meli_crawler/**"
      - "validation/**"
      - "requirements.txt"
      - ".env"
      - "!tests/**"
      - "!.venv/**"
      - "!node_modules/**"
      - "!.git/**"
      - "!__pycache__/**"
      - "!*.pyc"
      - "!.pytest_cache/**"
      - "!.coverage"
      - "!coverage_html/**"
      - "!.mypy_cache/**"
      - "!Makefile"
      - "!README.md"
      - "!pyproject.toml"
      - "!deploy-local.sh"
      - "!serverless.yml"
      - "!serverless.dev.yml"
      - "!serverless.prod.yml"
  dotenv:
    path: .env
    include:
      - ZYTE_API_KEY
      - OPENAI_API_KEY
